### ISSUE TITLE
How to grant the aws-accounts-to-cmdb lambda function access to call the organization.ListAccounts  API

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel#87]
Here is the current error:
`botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListAccounts operation: You don't have permissions to access this resource.`

**Comment by dsw88** [comment]
I forgot that this application needs read access to organizations APIs. A good way to handle this might be to add a new service type "apiaccess" that allows you to grant applications read-only access to one or more services.

Here's an example of that using the aws-accounts-to-cmdb Handel file:
```
version: 1

name: accounts-to-cmdb

environments:
  prd:
    function:
      type: lambda
      path_to_code: .
      handler: main.lambda_handler
      runtime: python3.6
      memory: 128
      timeout: 60
      environment_variables:
        RUNNING_IN_LAMBDA: true
      dependencies:
      - orgaccess
    trigger:
      type: cloudwatchevent
      event_pattern:
        source:
        - aws.organizations
        detail-type:
        - AWS API Call via CloudTrail
        detail:
          eventSource:
          - organizations.amazonaws.com
      event_consumers:
      - service_name: function
    orgaccess:
      type: apiaccess # Grants READ-ONLY access to one or more AWS services
      aws_services:
      - organizations
```

So you can see the extra lines at the bottom specifying that you want access to the organizations API, then you consume that as a dependency in your Lambda function, which grants the Lambda permissions to use that service.

The other option is to not introduce a read-only access service like this in Handel and just require you to manually add those permissions after the fact. The downside to that approach is that anything that gets replaced needs to have the permissions manually added each time.
